<?xml version="1.0"?>
<package format="3">
  <name>control_link_contract</name>
  <version>0.1.0</version>
  <description>Typed contract, QoS, and endpoint compatibility support for ControlLink Guardian.</description>
  <maintainer email="zenglm707@gmail.com">zeng-lm-cgaga</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>yaml_cpp_vendor</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
